### ISSUE TITLE
Add margin to data details list

### ISSUE THREAD

**Issue by upperwal** [DataSpace-Mobility/smart-move-platform#6]
<img width="776" alt="Screenshot 2020-11-19 at 2 33 11 PM" src="https://user-images.githubusercontent.com/5246435/99644694-4230cf00-2a74-11eb-9f7d-0651ee6a4beb.png">

Add some margin between the list and input box.

**Comment by rishabhsisodiya** [comment]
@upperwal If recent changes look good to you then you can close this issue.
